//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "fabric"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    Serialize,
    Deserialize,
    ts_rs :: TS,
)]
#[serde(rename_all = "camelCase")]
#[ts(rename = "Fabric")]
#[ts(export_to = "../src/types/fabric.ts")]
pub struct Model {
    pub id: i32,
    pub name: Option<String>,
    pub length: Option<f32>,
    pub width: Option<f32>,
    pub costs: Option<f32>,
    pub foto_path: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Length,
    Width,
    Costs,
    FotoPath,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FabricXProject,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::None).def().null(),
            Self::Length => ColumnType::Float.def().null(),
            Self::Width => ColumnType::Float.def().null(),
            Self::Costs => ColumnType::Float.def().null(),
            Self::FotoPath => ColumnType::String(StringLen::None).def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FabricXProject => {
                Entity::has_many(super::fabric_x_project::Entity).into()
            }
        }
    }
}

impl Related<super::fabric_x_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FabricXProject.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        super::fabric_x_project::Relation::Project.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::fabric_x_project::Relation::Fabric.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
