//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::fabric::Entity as Fabric;
pub use super::fabric_x_project::Entity as FabricXProject;
pub use super::project::Entity as Project;
