//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "project"
    }
}

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveModel,
    DeriveActiveModel,
    Eq,
    Serialize,
    Deserialize,
    ts_rs :: TS,
)]
#[serde(rename_all = "camelCase")]
#[ts(rename = "Project")]
#[ts(export_to = "../../src/types/project.ts")]
pub struct Model {
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    FabricXProject,
    PatternXProject,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::FabricXProject => {
                Entity::has_many(super::fabric_x_project::Entity).into()
            }
            Self::PatternXProject => {
                Entity::has_many(super::pattern_x_project::Entity).into()
            }
        }
    }
}

impl Related<super::fabric_x_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FabricXProject.def()
    }
}

impl Related<super::pattern_x_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PatternXProject.def()
    }
}

impl Related<super::fabric::Entity> for Entity {
    fn to() -> RelationDef {
        super::fabric_x_project::Relation::Fabric.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::fabric_x_project::Relation::Project.def().rev())
    }
}

impl Related<super::pattern::Entity> for Entity {
    fn to() -> RelationDef {
        super::pattern_x_project::Relation::Pattern.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::pattern_x_project::Relation::Project.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
